package main

import (
  "fmt"
  "os"

  cardano "github.com/christianschmitz/cardano-suite"
)

// test the autogenerated serializer and deserializer for the Handshake messages
func main() {
  testMessage("HandshakeProposeVersions", cardano.NewHandshakeProposeVersions(cardano.TESTNET_MAGIC))

  testMessage("HandshakeAcceptVersion", &cardano.HandshakeAcceptVersion{
    0,
    0,
  })

  testMessage("HandshakeVersionMismatch", &cardano.HandshakeVersionMismatch{
    []int{3},
  })

  testMessage("HandshakeDecodeError", &cardano.HandshakeDecodeError{
    0,
    "decode error",
  })

  testMessage("HandshakeDecodeError", &cardano.HandshakeDecodeError{
    0,
    "decode error",
  })

  testMessage("HandshakeRefused", &cardano.HandshakeRefused{
    1,
    "handshake refused",
  })
}

func testMessage(type_ string, msg cardano.HandshakeMessage) {
  fmt.Fprintf(os.Stdout, "\nTesting %s", type_)

  b := cardano.HandshakeMessageToCBOR(msg) // it is very important to use this function, and not the struct specific ToCBOR

  fmt.Fprintf(os.Stdout, "CBOR: [")
  for i, x := range b {
    if i == len(b) - 1 {
      fmt.Fprintf(os.Stdout, "%02x", x)
    } else {
      fmt.Fprintf(os.Stdout, "%02x, ", x)
    }
  }
  fmt.Println("]")

  msg_, err := cardano.HandshakeMessageFromCBOR(b)
  if err != nil {
    panic(err)
  }

  fmt.Println("ORIG: ", msg_)
}

